// Generic actor (de)serializer (G1a). Mirrors the original's respawn keyed off getActorType():
//   serializeActor(e)  -> { typ, type, team, role, x, y, chain }  (the actor-type symbol + its saved chain)
//   respawnActor(snap) -> spawn from `typ` via the SHARED spawnFromSymbol routing, then restoreFromSave.
//
// spawnFromSymbol(sym, x, y) is the single source of truth for "a tile/actor-type symbol -> an Entity",
// factored OUT of RoomManager.spawnObjects so first-spawn and save-restore cannot drift (plan §C.1).
// It routes by the same branches RoomManager used: PICKUPS effect -> spawnPickup; #objDwelling ->
// spawnDwelling; else spawnUnit. The `#`-prefix is tolerated (tile symbols carry it; saved typ may not).

import type { Entity } from "../engine/dispatch";
import { registry } from "../game/data";
import { spriteCharOr } from "../components/anim";
import { Team } from "../components/combat";
import { spawnUnit, spawnDwelling, spawnPickup, type PickupSym } from "./archetypes";
import { PICKUPS } from "../world/spawnTable";

/** A saved actor: its respawn key + the runtime type/team/role (re-applied on respawn) + its chain. */
export interface ActorSave {
  typ: string;            // getActorType — the respawn key (bare name or pickup-effect key)
  type: string;          // entity.type at save time (player/enemy/ally/dwelling/pickup)
  team: string;          // Team.team (a summoned ally is a #monsters actor forced onto #aldevar)
  role: string;          // Team.role (#teamMembers / #teamBuildings)
  x: number; y: number;  // belt-and-braces position (chain also round-trips it via Movement.move)
  chain: Record<string, any>;
  rel?: RelSave;         // committed-target locator (G1c) — never an entity id
  teleportable?: boolean;// pTeleportable: a summoned ally re-banks on room-leave (G2)
}

// G1c: a committed reference (CpuAI #target) saved as a POSITIONAL locator, re-acquired by spatial
// query on load. NEVER an entity id (regenerated by makeEntityId, would dangle).
export interface RelSave { team: string; role: string; x: number; y: number; }

const bare = (s: string): string => s.replace(/^#/, "");

/** spawnFromSymbol: the shared tile/actor-type-symbol routing (used by RoomManager AND respawnActor). */
export function spawnFromSymbol(sym: string, x: number, y: number): Entity | null {
  const withHash = sym.startsWith("#") ? sym : "#" + sym;
  const name = bare(sym);
  if (PICKUPS[withHash]) return spawnPickup(PICKUPS[withHash]!, x, y);
  // a pickup may also be saved by its bare effect key (actorType = the effect)
  if (isPickupEffect(name)) return spawnPickup(name as PickupSym, x, y);
  if (registry.resolveActor(name)?.["objType"] === "#objDwelling") {
    return spawnDwelling(name, x, y, spriteCharOr(name));
  }
  if (registry.resolveActor(name)) return spawnUnit(name, x, y, { animChar: spriteCharOr(name) });
  return null;
}

const PICKUP_EFFECTS = new Set<string>([
  "heal", "speed", "sword", "spell", "manaCapacity", "manaFlow", "manaBurst",
  "cBlast", "darkBlast", "arcticBlast", "healBlast", "armySummon", "monsterSummon", "energyMines",
]);
function isPickupEffect(name: string): boolean { return PICKUP_EFFECTS.has(name); }

/** serializeActor: { typ, type, team, role, x, y, chain } for any spawned actor. */
export function serializeActor(e: Entity): ActorSave {
  const chain: Record<string, any> = {};
  e.send("addSaveData", chain); // each component folds its namespaced slice
  const pos = (e.send("getPos") as { x: number; y: number } | undefined) ?? { x: 0, y: 0 };
  // committed-target locator (G1c): only AI actors answer getTargetDetails; never an entity id.
  const rel = (e.send("getTargetDetails") as RelSave | null | undefined) ?? undefined;
  return {
    typ: (e.send("getActorType") as string) || "",
    type: e.type,
    team: (e.send("getTeam") as string) || "",
    role: (e.send("getTeamRole") as string) || "#teamMembers",
    x: pos.x, y: pos.y,
    chain,
    ...(rel ? { rel } : {}),
    ...(e.flags.has("teleportable") ? { teleportable: true } : {}),
  };
}

/** respawnActor: spawn from the saved typ at the saved loc, re-apply runtime type/team, restore chain. */
export function respawnActor(snap: ActorSave): Entity | null {
  const e = spawnFromSymbol(snap.typ, snap.x, snap.y);
  if (!e) return null;
  // re-apply the runtime type (a summoned ally is a #monsters unit forced onto #aldevar — spawnUnit
  // would route it as an enemy, so honor the saved type + team faithfully).
  e.type = snap.type || e.type;
  const team = e.tryGet(Team);
  if (team && snap.team) { team.team = snap.team; }
  if (team && snap.role) { team.role = snap.role; }
  if (snap.teleportable) e.flags.add("teleportable"); else e.flags.delete("teleportable");
  e.send("restoreFromSave", snap.chain); // overwrite energy/level/position/weapon inventory etc.
  return e;
}
