// Runtime access to the parsed game data (generated by `npm run parse-data`). Builds the
// registry so spawns pull real act_*.txt stats (#inherit + #attack resolved).
import dataJson from "../generated/data.json";
import { Registry, type DataFileLike } from "../data/registry";

export const registry = new Registry(dataJson as unknown as Record<string, DataFileLike>);
