// Packs the single-chunk vite build (dist/game.js) + every file under public/assets into ONE
// self-contained HTML file. All assets become data: URLs in an embedded map; a small bootstrap
// shim rewrites the three ways the engine reaches for assets — fetch("/assets/..."), Image.src,
// and Audio/HTMLMediaElement.src — so the game runs with zero network requests (gist raw, file://,
// anywhere). Game code is untouched.
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const assetsDir = join(root, "public/assets");
const gameJs = readFileSync(join(root, "dist/game.js"), "utf8");

const MIME: Record<string, string> = {
  png: "image/png", wav: "audio/wav", mp3: "audio/mpeg", txt: "text/plain",
};

function walk(dir: string, out: string[] = []): string[] {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

const files = walk(assetsDir);
const map: Record<string, string> = {};
let bytes = 0;
for (const f of files) {
  const key = relative(assetsDir, f).split("\\").join("/");
  const ext = key.slice(key.lastIndexOf(".") + 1).toLowerCase();
  const mime = MIME[ext] ?? "application/octet-stream";
  const buf = readFileSync(f);
  bytes += buf.length;
  map[key] = `data:${mime};base64,${buf.toString("base64")}`;
}
console.log(`embedding ${files.length} assets, ${(bytes / 1048576).toFixed(1)}MB raw`);

const bootstrap = `
<script>
// --- single-file asset shim (generated by tools/pack_singlefile.ts) ---
(function () {
  var A = window.__MR_ASSETS__;
  function map(url) {
    if (typeof url !== "string") return null;
    var i = url.indexOf("/assets/");
    if (i < 0) return null;
    var key = url.slice(i + 8).split("?")[0].split("#")[0];
    return A[key] || null;
  }
  var origFetch = window.fetch.bind(window);
  window.fetch = function (input, init) {
    var url = typeof input === "string" ? input : (input && input.url);
    var d = map(url);
    return origFetch(d != null ? d : input, init);
  };
  function patchSrc(proto) {
    var desc = Object.getOwnPropertyDescriptor(proto, "src");
    if (!desc || !desc.set) return;
    Object.defineProperty(proto, "src", {
      configurable: true, enumerable: desc.enumerable,
      get: desc.get,
      set: function (v) { var d = map(v); desc.set.call(this, d != null ? d : v); },
    });
  }
  patchSrc(HTMLImageElement.prototype);
  patchSrc(HTMLMediaElement.prototype);
})();
</script>`;

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Merlin's Revenge</title>
    <style>
      html, body { margin: 0; background: #111; height: 100%; }
      #app { display: flex; align-items: center; justify-content: center; height: 100%; }
      canvas { image-rendering: pixelated; background: #000; }
    </style>
    <script>window.__MR_ASSETS__ = ${JSON.stringify(map)};</script>${bootstrap}
  </head>
  <body>
    <div id="app"><canvas id="game"></canvas></div>
    <script type="module">${gameJs}</script>
  </body>
</html>
`;

const out = join(root, "dist/merlins-revenge.html");
writeFileSync(out, html);
console.log(`wrote ${out} — ${(html.length / 1048576).toFixed(1)}MB`);
